Repository TokTok/hs-toxcore, pull requests merged in 2022-02, with the labels that each got.

#200 cleanup: Mark NodeList as Safe Haskell.
  src/Network/Tox/DHT/NodeList.lhs
Labels: cleanup

#202 chore: Use toktok-stack image for haskell stack builds.
  .github/docker/Dockerfile
Labels: chore

#205 cleanup: Remove all unused imports.
  BUILD.bazel
  src/Data/Binary/Bits/Get.hs
  src/Data/Binary/Bits/Put.hs
  src/Network/Tox/Binary.hs
  src/Network/Tox/Crypto/Box.lhs
  src/Network/Tox/Crypto/Key.lhs
  src/Network/Tox/Crypto/KeyPair.lhs
  src/Network/Tox/Crypto/Keyed.hs
  src/Network/Tox/Crypto/KeyedT.hs
  src/Network/Tox/Crypto/Nonce.lhs
  src/Network/Tox/DHT/ClientList.lhs
  src/Network/Tox/DHT/ClientNode.lhs
  src/Network/Tox/DHT/DhtPacket.lhs
  src/Network/Tox/DHT/DhtRequestPacket.lhs
  src/Network/Tox/DHT/DhtState.lhs
  src/Network/Tox/DHT/Distance.lhs
  src/Network/Tox/DHT/KBuckets.lhs
  src/Network/Tox/DHT/NodeList.lhs
  src/Network/Tox/DHT/NodesRequest.lhs
  src/Network/Tox/DHT/NodesResponse.lhs
  src/Network/Tox/DHT/Operation.lhs
  src/Network/Tox/DHT/RpcPacket.lhs
  src/Network/Tox/Network/MonadRandomBytes.hs
  src/Network/Tox/Network/Networked.hs
  src/Network/Tox/NodeInfo/HostAddress.lhs
  src/Network/Tox/NodeInfo/NodeInfo.lhs
  src/Network/Tox/NodeInfo/PortNumber.lhs
  src/Network/Tox/NodeInfo/SocketAddress.lhs
  src/Network/Tox/Protocol/Packet.lhs
  src/Network/Tox/SaveData.lhs
  src/Network/Tox/SaveData/DHT.lhs
  src/Network/Tox/SaveData/Friend.lhs
  src/Network/Tox/Time.hs
  src/Network/Tox/Timed.hs
  src/Network/Tox/TimedT.hs
  test/Data/Result.hs
  test/Network/Tox/Crypto/BoxSpec.hs
  test/Network/Tox/Crypto/CombinedKeySpec.hs
  test/Network/Tox/Crypto/KeyPairSpec.hs
  test/Network/Tox/Crypto/KeySpec.hs
  test/Network/Tox/CryptoSpec.hs
  test/Network/Tox/DHT/ClientListSpec.hs
  test/Network/Tox/DHT/DhtRequestPacketSpec.hs
  test/Network/Tox/DHT/DistanceSpec.lhs
  test/Network/Tox/DHT/KBucketsSpec.hs
  test/Network/Tox/DHT/OperationSpec.hs
  test/Network/Tox/DHT/PendingRepliesSpec.hs
  test/Network/Tox/DHTSpec.hs
  test/Network/Tox/EncodingSpec.hs
  test/Network/Tox/NodeInfoSpec.hs
  test/Network/Tox/ProtocolSpec.hs
  toxcore.cabal
Labels: cleanup

#207 chore: Allow higher versions of msgpack-types.
  .github/settings.yml
  .github/workflows/ci.yml
  stack.yaml
  toxcore.cabal
Labels: chore

#196 docs: update NGC packet spec to reflect recent changes
  src/Network/Tox/Application/GroupChats.lhs
  src/Network/Tox/Application/GroupChatsPackets.lhs
Labels: documentation
